Лабораторна робота №1
Тема: Операції над масивами та матрицями в Python (NumPy)
Виконав: Яцкий Андрій
Варіант: 28

# Завдання 1 (Варіант 28)
 Створюємо одновимірний масив зі значеннями n! (факторіал) кожного натурального числа n

In [3]:
import numpy as np
import math

# Кількість елементів у векторі
k = 10
factorials = np.array([math.factorial(i) for i in range(1, k+1)], dtype=object)

print("Вектор факторіалів n! для n = 1..10:\n", factorials)


Вектор факторіалів n! для n = 1..10:
 [1 2 6 24 120 720 5040 40320 362880 3628800]


# Завдання 2 (Варіант 28)
 Створюємо матрицю 3x3 з оберненими значеннями косинусів натуральних чисел

In [4]:
import numpy as np

numbers = np.arange(1, 10).reshape(3,3)
matrix = 1 / np.cos(numbers)  # обернене значення косинуса

print("Матриця з 1/cos(n):\n", matrix)

Матриця з 1/cos(n):
 [[ 1.85081572 -2.40299796 -1.01010867]
 [-1.52988566  3.52532009  1.04148193]
 [ 1.3264319  -6.87285064 -1.09753791]]


# Завдання 3 (Варіант 28)
 Масив 3x3 з випадковими числами від -1 до 1. Обчислити відсоток від’ємних.

In [ ]:
import numpy as np

A = np.random.uniform(-1, 1, (3,3))
neg_percent = np.sum(A < 0) / A.size * 100

print("Матриця A:\n", A)
print(f"\nВідсоток від’ємних елементів: {neg_percent:.2f}%")

# Завдання 4 (Варіант 28)
 Масив 3x3 з випадковими дійсними числами в діапазоні [-1.4, 1.4]

In [5]:
import numpy as np

A = np.random.uniform(-1.4, 1.4, (3,3))
print("Матриця A:\n", A)

Матриця A:
 [[-1.20109904 -1.15603796 -1.34338849]
 [ 0.93133557  0.7788389   1.03603402]
 [ 1.34013136  0.83764398 -0.10785779]]


# Завдання 5 (Варіант 28)
 Два одновимірні масиви (розмір 5), випадкові цілі числа від 2 до 7.
 Виконуємо додавання, віднімання, множення поелементно.

In [6]:
import numpy as np

a = np.random.randint(2, 8, size=5)
b = np.random.randint(2, 8, size=5)

print("a:", a)
print("b:", b)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)

a: [5 5 2 3 3]
b: [3 2 4 6 5]
a + b = [8 7 6 9 8]
a - b = [ 2  3 -2 -3 -2]
a * b = [15 10  8 18 15]


# Завдання 6 (Варіант 28)
 Створюємо дві матриці 4x4 з випадковими цілими числами від 3 до 13
та знаходимо їхній матричний добуток.

In [7]:
import numpy as np

A = np.random.randint(3, 14, (4,4))
B = np.random.randint(3, 14, (4,4))
C = A @ B

print("A:\n", A)
print("\nB:\n", B)
print("\nA @ B:\n", C)

A:
 [[ 5 10  5  3]
 [ 3  7  8  8]
 [ 9 11  7  4]
 [ 7 12 13 13]]

B:
 [[11  4  4 10]
 [12 12  6  9]
 [10  5  3  6]
 [ 8 12 13  7]]

A @ B:
 [[249 201 134 191]
 [261 232 182 197]
 [333 251 175 259]
 [455 393 308 347]]


# Завдання 7 (Варіант 28)
 Створюємо матриці 2x3 і 3x4 з випадковими числами 1–4 та перемножаємо їх.

In [ ]:
import numpy as np

A = np.random.randint(1, 5, (2,3))
B = np.random.randint(1, 5, (3,4))
C = A @ B

print("A (2x3):\n", A)
print("\nB (3x4):\n", B)
print("\nA @ B (2x4):\n", C)

# Завдання 8 (Варіант 28)
 Створюємо матрицю 3x3 з випадковими цілими числами 1–15 і знаходимо обернену матрицю.

In [8]:
import numpy as np

A = np.random.randint(1, 16, (3,3)).astype(float)
det = np.linalg.det(A)

print("A:\n", A)
print("\nВизначник det(A) =", det)

if abs(det) < 1e-8:
    print("\nМатриця вироджена — оберненої не існує.")
else:
    A_inv = np.linalg.inv(A)
    print("\nОбернена матриця A^-1:\n", A_inv)

A:
 [[12.  5.  7.]
 [ 5.  5.  4.]
 [13.  5.  5.]]

Визначник det(A) = -85.00000000000001

Обернена матриця A^-1:
 [[-0.05882353 -0.11764706  0.17647059]
 [-0.31764706  0.36470588  0.15294118]
 [ 0.47058824 -0.05882353 -0.41176471]]


# Завдання 9 (Варіант 28)
 Створюємо матрицю 7x7 з випадковими дійсними числами від 0 до 10 і транспонуємо її.

In [9]:
import numpy as np

M = np.random.random((7,7)) * 10

print("Матриця M:\n", M)
print("\nТранспонована матриця M^T:\n", M.T)

Матриця M:
 [[2.53291603 4.66310773 2.44425592 1.58969584 1.10375141 6.56329589
  1.38182951]
 [1.96582362 3.68725171 8.2099323  0.97101276 8.37944907 0.96098408
  9.76459465]
 [4.68651202 9.76761088 6.0484552  7.39263579 0.39187792 2.82806963
  1.20196561]
 [2.96140198 1.18727719 3.17983179 4.14262995 0.64147496 6.92472119
  5.66601454]
 [2.65389491 5.23248053 0.93940511 5.75946496 9.29296198 3.18568952
  6.6741038 ]
 [1.31797862 7.16327204 2.89406093 1.83191362 5.86512935 0.20107546
  8.28940029]
 [0.04695476 6.77816537 2.70007973 7.35194022 9.62188545 2.48753144
  5.76157334]]

Транспонована матриця M^T:
 [[2.53291603 1.96582362 4.68651202 2.96140198 2.65389491 1.31797862
  0.04695476]
 [4.66310773 3.68725171 9.76761088 1.18727719 5.23248053 7.16327204
  6.77816537]
 [2.44425592 8.2099323  6.0484552  3.17983179 0.93940511 2.89406093
  2.70007973]
 [1.58969584 0.97101276 7.39263579 4.14262995 5.75946496 1.83191362
  7.35194022]
 [1.10375141 8.37944907 0.39187792 0.64147496 9.29296198

# Завдання 10 (Варіант 28)
 Створюємо матрицю 3x4 з випадковими дійсними числами від 0 до 1
 і вектор 4x1 з випадковими цілими числами 1–10, знаходимо їх добуток.

In [10]:
import numpy as np

A = np.random.random((3,4))
v = np.random.randint(1, 11, (4,1))
res = A @ v

print("Матриця A:\n", A)
print("\nВектор v:\n", v)
print("\nA @ v:\n", res)

Матриця A:
 [[0.59204193 0.57225191 0.22308163 0.95274901]
 [0.44712538 0.84640867 0.69947928 0.29743695]
 [0.81379782 0.39650574 0.8811032  0.58127287]]

Вектор v:
 [[ 6]
 [10]
 [ 1]
 [10]]

A @ v:
 [[19.02534239]
 [14.82068778]
 [15.54167625]]


# Завдання 11 (Варіант 28)
Створюємо матрицю 2x3 і вектор 3x1, обидва заповнені випадковими дійсними числами 0–1.
Обчислюємо добуток матриці на вектор.

In [11]:
import numpy as np

A = np.random.random((2,3))
v = np.random.random((3,1))
res = A @ v

print("Матриця A:\n", A)
print("\nВектор v:\n", v)
print("\nA @ v:\n", res)

Матриця A:
 [[0.50132438 0.95608363 0.6439902 ]
 [0.42385505 0.60639321 0.0191932 ]]

Вектор v:
 [[0.30157482]
 [0.66017354]
 [0.29007761]]

A @ v:
 [[0.96917506]
 [0.53371628]]


# Завдання 12 (Варіант 28)
Створюємо дві матриці 3x3 з випадковими числами 1–3 та обчислюємо різницю A - B.

In [12]:
import numpy as np

A = np.random.randint(1, 4, (3,3))
B = np.random.randint(1, 4, (3,3))
D = A - B

print("A:\n", A)
print("\nB:\n", B)
print("\nA - B:\n", D)

A:
 [[2 3 1]
 [3 3 2]
 [2 2 3]]

B:
 [[1 1 2]
 [1 3 3]
 [1 3 3]]

A - B:
 [[ 1  2 -1]
 [ 2  0 -1]
 [ 1 -1  0]]


# Завдання 13 (Варіант 28)
 Створюємо дві матриці 3x3 з випадковими числами 1–5 та обчислюємо їх поелементний добуток.

In [13]:
import numpy as np

A = np.random.randint(1, 6, (3,3))
B = np.random.randint(1, 6, (3,3))
C = A * B

print("A:\n", A)
print("\nB:\n", B)
print("\nA * B (поелементно):\n", C)

A:
 [[4 1 4]
 [1 5 3]
 [4 5 1]]

B:
 [[3 4 4]
 [2 4 5]
 [4 4 2]]

A * B (поелементно):
 [[12  4 16]
 [ 2 20 15]
 [16 20  2]]


# Завдання 14 (Варіант 28)
 Створюємо матрицю 4x4 з випадковими цілими числами 1–100
 та знаходимо суму елементів побічної діагоналі.

In [14]:
import numpy as np

n = 4
M = np.random.randint(1, 101, (n,n))
anti_diag_sum = sum(M[i, n-1-i] for i in range(n))

print("Матриця M:\n", M)
print("\nСума побічної діагоналі:", anti_diag_sum)

Матриця M:
 [[74 42 24  4]
 [47 91 51  4]
 [32 10 11 28]
 [46 72 40 62]]

Сума побічної діагоналі: 111


# Завдання 15 (Варіант 28)
Створюємо матрицю 3x3 з випадковими дійсними числами від -2 до 2.
 Знаходимо найменші за модулем елементи у кожному стовпці та формуємо вектор-стовпчик.

In [15]:
import numpy as np

M = np.random.uniform(-2, 2, (3,3))
idx = np.argmin(np.abs(M), axis=0)
v = M[idx, range(M.shape[1])].reshape(-1,1)

print("Матриця M:\n", M)
print("\nІндекси мінімумів за модулем:", idx)
print("\nВектор-стовпчик мінімальних за модулем значень:\n", v)

Матриця M:
 [[ 0.91996225 -1.31348129  0.08414642]
 [-1.78264805 -1.2000139  -1.92591282]
 [ 1.17479081 -1.10430125 -0.61859328]]

Індекси мінімумів за модулем: [0 2 0]

Вектор-стовпчик мінімальних за модулем значень:
 [[ 0.91996225]
 [-1.10430125]
 [ 0.08414642]]


# Висновок:
 У ході виконання лабораторної роботи №1 (варіант 28) було реалізовано 15 завдань,
 що продемонстрували основні операції над масивами та матрицями в бібліотеці NumPy.
 Виконано обчислення з випадковими числами, транспонування, множення, різницю,
знаходження відсотків, факторіалів, побічних діагоналей та обернених матриць.
 Отримано практичні навички програмування та чисельних обчислень у Python.